USE Proyecto2;

SELECT 'Municipios' AS TABLAS, COUNT(*) AS TOTALES FROM municipio UNION
SELECT 'Departamentos' AS TABLAS, COUNT(*) AS TOTALES FROM departamento UNION
SELECT 'Paises' AS TABLAS, COUNT(*) AS TOTALES FROM pais UNION
SELECT 'Razas' AS TABLAS, COUNT(*) AS TOTALES FROM raza UNION
SELECT 'Partidos' AS TABLAS, COUNT(*) AS TOTALES FROM partido UNION
SELECT 'Elecciones' AS TABLAS, COUNT(*) AS TOTALES FROM eleccion;